version: '3'
services:
    vue-app:
        build:
            context: .  # Use the current directory as the build context
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - NODE_ENV=production  # Set NODE_ENV to production for Vue app

